# Generated by Django 2.2.4 on 2019-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/%Y/%m', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='experiences',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='图片'),
        ),
    ]
