# Generated by Django 2.2.4 on 2019-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190901_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(default='RexDu', max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article/%Y/%m', verbose_name='图片'),
        ),
    ]
