# Generated by Django 2.2.4 on 2019-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190903_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('linux', 'Linux'), ('other', 'Other')], max_length=10, verbose_name='类别'),
        ),
    ]
