# Generated by Django 2.2.4 on 2019-09-05 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190903_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadAndPraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='用户IP')),
                ('article_id', models.IntegerField(default=0, verbose_name='数据id')),
                ('category', models.IntegerField(choices=[(1, '文章'), (2, '分享'), (3, '其它')], default=1, verbose_name='收藏类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('read_nums', models.IntegerField(default=0, verbose_name='已读次数')),
                ('is_praise', models.BooleanField(default=False, verbose_name='是否点赞')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='article',
            name='praise_nums',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
