# Generated by Django 2.2.4 on 2019-09-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190907_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Category', verbose_name='类别'),
        ),
    ]
