# Generated by Django 2.2.4 on 2019-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190907_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='home.Tag', verbose_name='标签'),
        ),
    ]
