# Generated by Django 2.2.4 on 2019-10-24 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190917_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='访客IP')),
                ('visit_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='访问时间')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
            },
        ),
    ]
