# Generated by Django 2.2.4 on 2020-06-20 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='系列名')),
                ('count', models.IntegerField(default=0, verbose_name='包含文章数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='readandpraise',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Series', verbose_name='系列'),
        ),
    ]
