# Generated by Django 2.2.4 on 2020-06-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200620_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': '系列文章', 'verbose_name_plural': '系列文章'},
        ),
    ]
