# Generated by Django 2.2.4 on 2020-06-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200620_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='count',
        ),
    ]
